name: Angular App Deployment

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
  
    # - name: Change directory to hello-app
    #   run: ./home/runner/work/Angular_18/Angular_18/hello-app/package.json
  
    - name: Install dependencies
      run:  npm install
      working-directory: ./hello-app
      
    - name: Build Angular app
      run: npm run build --prod
      working-directory: ./hello-app

    - name: Deploy to AWS EC2
      if: github.ref == 'refs/heads/main' # Change this to your default branch if necessary
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa
        
    - name: Transfer files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -r dist/hello-app/* $REMOTE_USER@$REMOTE_HOST:$REMOTE_DIR

    - name: Start application on EC2
      run: |
        ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST << 'EOF'
          cd $REMOTE_DIR
          nohup npx http-server -p 8080 &
        EOF
