name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  REMOTE_USER: ${{ secrets.REMOTE_USER }}
  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
  REMOTE_DIR: ${{ secrets.REMOTE_DIR }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies and build
      run: |
        npm install
        npm run build --prod

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa

    - name: Transfer files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -r dist/hello-app/* $REMOTE_USER@$REMOTE_HOST:$REMOTE_DIR

    - name: Start application on EC2
      run: |
        ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST << 'EOF'
          cd $REMOTE_DIR
          nohup npx http-server -p 8080 &
        EOF
